<?php

namespace SnappMarket\Tests\Units;

use Illuminate\Http\Request;
use SnappMarket\LaravelAuth\SMGuard;
use SnappMarket\LaravelAuth\SMUser;
use SnappMarket\LaravelAuth\SMUserProvider;
use SnappMarket\Auth\Communicator;
use SnappMarket\Tests\TestCase;

class SmGurdTest extends TestCase
{

    protected
        $identifierParameter,
        $identifierKeyParameter,
        $secretKey;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        config()->set('auth-communication.gateway.parameters.identifier', $this->identifierParameter = 'user_id');
        config()->set('auth-communication.gateway.parameters.key', $this->identifierKeyParameter = 'secret-token');
        config()->set('auth-communication.gateway.secret_key', $this->secretKey = 'AAJrv%r@2iL279nYf1r&Mht5rs');
    }

    /** @test */
    public function user()
    {
        $mockProvider = app(SMUserProvider::class);
        $mockCommunicator = \Mockery::mock(Communicator::class);

        $mockRequest = Request::create('/', 'GET', []);
        $mockRequest->headers->add([
            $this->identifierParameter => $userId = 1,
            $this->identifierKeyParameter => $this->secretKey
        ]);

        $SMGuard = new SMGuard($mockProvider, $mockCommunicator, $mockRequest);
        $result = $SMGuard->user();
        $this->assertInstanceOf(SMUser::class, $result);
        $this->assertEquals($result->getId(), $userId);
    }
}